/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import JInternalFrame.CadastroAluno;
import JInternalFrame.GerAluno;
import JInternalFrame.GerBoletim;
import JInternalFrame.GerProf;

/**
 *
 * @author Aluno
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        
        GerProf gf = new GerProf();
        janela.add(gf);
        gf.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        CadAluno = new javax.swing.JButton();
        GBoletim = new javax.swing.JButton();
        GProf = new javax.swing.JButton();
        janela = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        Titulo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Administração");
        getContentPane().add(Titulo);
        Titulo.setBounds(330, 10, 500, 68);

        CadAluno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CadAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/aluno.png"))); // NOI18N
        CadAluno.setText("Cadastrar Aluno");
        CadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(CadAluno);
        CadAluno.setBounds(20, 270, 300, 80);

        GBoletim.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GBoletim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/boletim.png"))); // NOI18N
        GBoletim.setText("Visualizar Boletins");
        GBoletim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GBoletimActionPerformed(evt);
            }
        });
        getContentPane().add(GBoletim);
        GBoletim.setBounds(20, 380, 300, 80);

        GProf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/prof.png"))); // NOI18N
        GProf.setText("Gerenciar Professores");
        GProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GProfActionPerformed(evt);
            }
        });
        getContentPane().add(GProf);
        GProf.setBounds(20, 160, 303, 80);

        janela.setPreferredSize(new java.awt.Dimension(900, 504));

        javax.swing.GroupLayout janelaLayout = new javax.swing.GroupLayout(janela);
        janela.setLayout(janelaLayout);
        janelaLayout.setHorizontalGroup(
            janelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        janelaLayout.setVerticalGroup(
            janelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        getContentPane().add(janela);
        janela.setBounds(340, 80, 900, 504);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Visualizar Alunos ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 480, 300, 90);

        voltar.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        voltar.setText("VOLTAR");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(10, 10, 140, 50);

        setSize(new java.awt.Dimension(1261, 675));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GProfActionPerformed
        GerProf gf = new GerProf();
        janela.add(gf);
        gf.setVisible(true);
    }//GEN-LAST:event_GProfActionPerformed

    private void CadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadAlunoActionPerformed
        CadastroAluno gf = new CadastroAluno();
        janela.add(gf);
        gf.setVisible(true);
    }//GEN-LAST:event_CadAlunoActionPerformed

    private void GBoletimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GBoletimActionPerformed
        GerBoletim gf = new GerBoletim();
        janela.add(gf);
        gf.setVisible(true);
    }//GEN-LAST:event_GBoletimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GerAluno gf = new GerAluno();
        janela.add(gf);
        gf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadAluno;
    private javax.swing.JButton GBoletim;
    private javax.swing.JButton GProf;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JDesktopPane janela;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
