/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.EscolaBean;
import connection.conexao;
import dao.EscolaDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro'S
 */
public class CadastroEscola extends javax.swing.JFrame {

    /**
     * Creates new form CadastroEscola
     */
    public CadastroEscola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JTextField();
        cep = new javax.swing.JTextField();
        cidade = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        dependencia = new javax.swing.JComboBox<>();
        bairro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        salvar = new javax.swing.JButton();
        deletar = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Escola");
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nome.setBorder(null);
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 390, 30));

        cep.setBorder(null);
        cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepActionPerformed(evt);
            }
        });
        getContentPane().add(cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 390, 30));

        cidade.setBorder(null);
        getContentPane().add(cidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 390, 30));

        endereco.setBorder(null);
        getContentPane().add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 380, 30));

        codigo.setBorder(null);
        getContentPane().add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 140, 30));

        dependencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estadual", "Municipal", "Particular" }));
        getContentPane().add(dependencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 130, 30));

        bairro.setBorder(null);
        getContentPane().add(bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 272, 390, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/tela.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        getContentPane().add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 150, 50));

        deletar.setText("Excluir");
        deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarActionPerformed(evt);
            }
        });
        getContentPane().add(deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 150, 50));

        atualizar.setText("Alterar");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        getContentPane().add(atualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 640, 140, 50));

        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, 150, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:

        if (cep.getText().equals("")
                || endereco.getText().equals("")
                || nome.getText().equals("")
                || String.valueOf(dependencia.getSelectedItem()).equals("")
                || codigo.getText().equals("")
                || cidade.getText().equals("")
                || bairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "ERRO", JOptionPane.ERROR_MESSAGE);

        } else {

            EscolaBean pb = new EscolaBean();
            EscolaDao pd = new EscolaDao();

            pb.setNome(nome.getText());
            pb.setCep(cep.getText());
            pb.setCodigo(codigo.getText());
            pb.setCidade(cidade.getText());
            pb.setBairro(bairro.getText());
            pb.setEndereco(endereco.getText());
            pb.setDependencia(String.valueOf(dependencia.getSelectedItem()));

            pd.create(pb);

            nome.setText("");
            cep.setText("");
            codigo.setText("");
            cidade.setText("");
            dependencia.setSelectedIndex(0);
            bairro.setText("");
            endereco.setText("");
        }

    }//GEN-LAST:event_salvarActionPerformed

    private void deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarActionPerformed
        EscolaDao ad = new EscolaDao();
        int matricula = Integer.parseInt(JOptionPane.showInputDialog("Digite o ID da escola para a confirmação da exclusão: "));

        ad.deletar(matricula);
    }//GEN-LAST:event_deletarActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        EscolaBean eb = new EscolaBean();
        EscolaDao ed = new EscolaDao();
        try {

            if (cep.getText().equals("")
                    || endereco.getText().equals("")
                    || nome.getText().equals("")
                    || String.valueOf(dependencia.getSelectedItem()).equals("")
                    || codigo.getText().equals("")
                    || cidade.getText().equals("")
                    || bairro.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos", "ERRO", JOptionPane.ERROR_MESSAGE);
            } else {
                int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o id da escola para atualização: "));

                eb.setNome(nome.getText());
                eb.setCep(cep.getText());
                eb.setCodigo(codigo.getText());
                eb.setCidade(cidade.getText());
                eb.setBairro(bairro.getText());
                eb.setEndereco(endereco.getText());
                eb.setDependencia(String.valueOf(dependencia.getSelectedItem()));

                ed.atualizar(eb, id);

                nome.setText("");
                cep.setText("");
                codigo.setText("");
                cidade.setText("");
                dependencia.setSelectedIndex(0);
                bairro.setText("");
                endereco.setText("");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Digite um id valido ","AVISO-LEGAL",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_atualizarActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        Connection con = conexao.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        try {
            int id = Integer.parseInt(JOptionPane.showInputDialog("Digite o id da escola para pesquisa: "));
            stmt = con.prepareStatement("SELECT * FROM escola WHERE id = '" + id + "'");
            rs = stmt.executeQuery();

            try {
                if (rs.next()) {
                    nome.setText(rs.getString("nome"));
                    bairro.setText(rs.getString("bairro"));
                    cidade.setText(rs.getString("cidade"));
                    cep.setText(rs.getString("cep"));
                    dependencia.setSelectedItem(rs.getString("dependencia"));
                    codigo.setText(rs.getString("codigo"));
                    endereco.setText(rs.getString("endereco"));

                } else {
                    JOptionPane.showMessageDialog(null, "EMAIL INVÁLIDO / CONTA NÃO EXISTE", "AVISO", JOptionPane.ERROR_MESSAGE);
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "EMAIL INVÁLIDO / CONTA NÃO EXISTE", "AVISO", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro na inserçao de dados");
        } finally {
            conexao.closeConnection(con, stmt, rs);
        }
    }//GEN-LAST:event_pesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEscola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEscola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar;
    private javax.swing.JTextField bairro;
    private javax.swing.JTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField codigo;
    private javax.swing.JButton deletar;
    private javax.swing.JComboBox<String> dependencia;
    private javax.swing.JTextField endereco;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nome;
    private javax.swing.JButton pesquisar;
    private javax.swing.JButton salvar;
    // End of variables declaration//GEN-END:variables
}
