/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ProfessorBean;
import connection.conexao;
import dao.ProfessorDao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import view.sub_view.ListarEscolas;
import view.sub_view.ListarProfessores;

/**
 *
 * @author Aluno
 */
public class CadastroProfessor extends javax.swing.JFrame {

    /**
     * Creates new form LoginProf
     */
    public CadastroProfessor() {
        initComponents();
    }

    private void pesquisarDados(String email) {
        Connection con = conexao.getConnection();
        PreparedStatement stmt = null;
        ResultSet rs = null;

        try {
            stmt = con.prepareStatement("SELECT * FROM professores WHERE email = '" + email + "'");
            rs = stmt.executeQuery();
            
            if(rs.next()){
                nome.setText(rs.getString("nome"));
                this.email.setText(rs.getString("email"));
                telefone.setText(rs.getString("telefone"));
                escola_pertencente.setText(rs.getString("escola_per"));
                disciplina.setSelectedItem(rs.getString("disciplina"));
                senha.setText(rs.getString("senha"));
            }else{
                JOptionPane.showMessageDialog(null,"EMAIL INVÁLIDO / CONTA NÃO EXISTE","AVISO",JOptionPane.ERROR_MESSAGE);
            }
            
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"EMAIL INVÁLIDO / CONTA NÃO EXISTE","AVISO",JOptionPane.ERROR_MESSAGE);
        }finally
        {
            conexao.closeConnection(con, stmt, rs);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JTextField();
        telefone = new javax.swing.JTextField();
        escola_pertencente = new javax.swing.JTextField();
        disciplina = new javax.swing.JComboBox<>();
        confirmar_senha = new javax.swing.JPasswordField();
        email = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnPesquisarESCOLA = new javax.swing.JLabel();
        pesquisarProfessor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        nome.setBorder(null);
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome);
        nome.setBounds(170, 230, 150, 15);

        telefone.setBorder(null);
        telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefoneActionPerformed(evt);
            }
        });
        getContentPane().add(telefone);
        telefone.setBounds(170, 370, 140, 20);

        escola_pertencente.setBorder(null);
        getContentPane().add(escola_pertencente);
        escola_pertencente.setBounds(170, 430, 380, 20);

        disciplina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Português", "Matemática", "Biologia", "Física", "Química", "Ed. Física", "Inglês", "Espanhol", "Geografia", "Filosofia", "Sociologia", "História" }));
        getContentPane().add(disciplina);
        disciplina.setBounds(470, 370, 130, 24);

        confirmar_senha.setBorder(null);
        getContentPane().add(confirmar_senha);
        confirmar_senha.setBounds(460, 300, 130, 15);

        email.setBorder(null);
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(170, 300, 160, 20);

        senha.setBorder(null);
        getContentPane().add(senha);
        senha.setBounds(440, 230, 150, 15);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Clique na lupa para efetuar uma pesquisa de dados");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 170, 410, 30);

        btnPesquisarESCOLA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/IconePesquisarEscola.png"))); // NOI18N
        btnPesquisarESCOLA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarESCOLAMouseClicked(evt);
            }
        });
        getContentPane().add(btnPesquisarESCOLA);
        btnPesquisarESCOLA.setBounds(570, 410, 60, 60);

        pesquisarProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/IconePesquisarProfessor.png"))); // NOI18N
        pesquisarProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisarProfessorMouseClicked(evt);
            }
        });
        getContentPane().add(pesquisarProfessor);
        pesquisarProfessor.setBounds(530, 160, 60, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/StyleCadastroProfessor.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 670, 616);

        editar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editar.setText("EDITAR DADOS");
        editar.setBorderPainted(false);
        editar.setContentAreaFilled(false);
        editar.setDefaultCapable(false);
        editar.setFocusPainted(false);
        editar.setFocusable(false);
        editar.setRequestFocusEnabled(false);
        editar.setVerifyInputWhenFocusTarget(false);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        getContentPane().add(editar);
        editar.setBounds(350, 510, 170, 50);

        cadastrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cadastrar.setText("CADASTRAR DADOS");
        cadastrar.setBorderPainted(false);
        cadastrar.setContentAreaFilled(false);
        cadastrar.setDefaultCapable(false);
        cadastrar.setFocusPainted(false);
        cadastrar.setFocusable(false);
        cadastrar.setRequestFocusEnabled(false);
        cadastrar.setVerifyInputWhenFocusTarget(false);
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrar);
        cadastrar.setBounds(100, 510, 190, 50);

        voltar.setText("jButton3");
        voltar.setBorderPainted(false);
        voltar.setContentAreaFilled(false);
        voltar.setDefaultCapable(false);
        voltar.setFocusPainted(false);
        voltar.setFocusable(false);
        voltar.setRequestFocusEnabled(false);
        voltar.setVerifyInputWhenFocusTarget(false);
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(10, 174, 73, 40);

        setSize(new java.awt.Dimension(668, 641));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed

        //Validar Email
        int v = 0;

        for (int i = 0; i < email.getText().length(); i++) {
            if (email.getText().charAt(i) == '@' && email.getText().endsWith("@gmail.com")) {
                v = v + 1;
            }
        }

        if (v == 1) {

            if (email.getText().equals("")
                    || String.valueOf(senha.getPassword()).equals("")
                    || nome.getText().equals("")
                    || String.valueOf(disciplina.getSelectedItem()).equals("")
                    || escola_pertencente.getText().equals("")
                    || String.valueOf(confirmar_senha.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            } else if (!(String.valueOf(confirmar_senha.getPassword()).equals(String.valueOf(senha.getPassword())))) {
                JOptionPane.showMessageDialog(null, "Campos não Coincidem", "AVISO", JOptionPane.ERROR_MESSAGE);
            } else {

                ProfessorBean pb = new ProfessorBean();
                ProfessorDao pd = new ProfessorDao();

                pb.setNome(nome.getText());
                pb.setEmail(email.getText());
                pb.setSenha(String.valueOf(senha.getPassword()));
                pb.setTelefone(telefone.getText());
                pb.setEscola_pertencente(escola_pertencente.getText());
                pb.setDisciplina(String.valueOf(disciplina.getSelectedItem()));

                pd.create(pb);

                nome.setText("");
                email.setText("");
                telefone.setText("");
                escola_pertencente.setText("");
                disciplina.setSelectedIndex(0);
                senha.setText("");
                confirmar_senha.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Email Inválido", "AVISO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed

        //Validar Email
        int v = 0;

        for (int i = 0; i < email.getText().length(); i++) {
            if (email.getText().charAt(i) == '@' && email.getText().endsWith("@gmail.com")) {
                v = v + 1;
            }
        }

        if (v == 1) {

            if (email.getText().equals("")
                    || String.valueOf(senha.getPassword()).equals("")
                    || nome.getText().equals("")
                    || String.valueOf(disciplina.getSelectedItem()).equals("")
                    || escola_pertencente.getText().equals("")
                    || String.valueOf(confirmar_senha.getPassword()).equals("")) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            } else if (!(String.valueOf(confirmar_senha.getPassword()).equals(String.valueOf(senha.getPassword())))) {
                JOptionPane.showMessageDialog(null, "Campos não Coincidem");
            } else {

                ProfessorBean pb = new ProfessorBean();
                ProfessorDao pd = new ProfessorDao();

                String email = JOptionPane.showInputDialog("Digite seu antigo Email: ");

                pb.setNome(nome.getText());
                pb.setEmail(this.email.getText());
                pb.setSenha(String.valueOf(senha.getPassword()));
                pb.setTelefone(telefone.getText());
                pb.setEscola_pertencente(escola_pertencente.getText());
                pb.setDisciplina(String.valueOf(disciplina.getSelectedItem()));
                pb.setSenha(String.valueOf(senha.getPassword()));

                pd.atualizar(pb, email);

                nome.setText(pb.getNome());
                this.email.setText(pb.getEmail());
                senha.setText(pb.getSenha());
                telefone.setText(pb.getTelefone());
                escola_pertencente.setText(pb.getEscola_pertencente());
                senha.setText(pb.getSenha());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Email Inválido", "AVISO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editarActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        new Admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed

    private void btnPesquisarESCOLAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarESCOLAMouseClicked
        ListarEscolas le = new ListarEscolas(this);
        
        le.resgatarNome(escola_pertencente.getText());
        le.setVisible(true);
        
    }//GEN-LAST:event_btnPesquisarESCOLAMouseClicked

    private void pesquisarProfessorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisarProfessorMouseClicked
        new ListarProfessores(this).setVisible(true);
    }//GEN-LAST:event_pesquisarProfessorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnPesquisarESCOLA;
    private javax.swing.JButton cadastrar;
    public javax.swing.JPasswordField confirmar_senha;
    public javax.swing.JComboBox<String> disciplina;
    private javax.swing.JButton editar;
    public javax.swing.JTextField email;
    public javax.swing.JTextField escola_pertencente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField nome;
    private javax.swing.JLabel pesquisarProfessor;
    public javax.swing.JPasswordField senha;
    public javax.swing.JTextField telefone;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
